# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  asc_key_content = ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
  asc_issuer_id = ENV["APP_STORE_CONNECT_ISSUER_ID"]
  asc_key_id = ENV["APP_STORE_CONNECT_API_KEY_ID"]
  keychain_pass = ENV["KEYCHAIN_PASS"]
  is_ci = ENV["CI"]

  desc "Push a new beta build to TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: asc_key_id,
      issuer_id: asc_issuer_id,
      key_content: asc_key_content
    )
    if is_ci 
      # Create a keychain because Github Action machines don't come with one
      create_keychain(
          name: "keychain",
          password: keychain_pass,
          default_keychain: true,
          unlock: true,
          timeout: 3600,
          lock_when_sleeps: false
      )
      match(
          type: "appstore",  
	  readonly: true,
          keychain_name: "keychain",
          keychain_password: "123456"
        )
    else
      match(type: "appstore", readonly: is_ci)
    end
    increment_build_number(xcodeproj: "Nos.xcodeproj")
    version_number = get_version_number(
      xcodeproj: "Nos.xcodeproj",
      target: "Nos"
    )
    build_number = get_build_number
    gym(
      scheme: "Nos", 
      clean: true,
      xcargs: "-skipPackagePluginValidation"
    )
    changelog = read_changelog
    upload_to_testflight(changelog: changelog)
    stamp_changelog(section_identifier: "#{version_number} (#{build_number})")
    git_commit(message: "TestFlight deployment", path: "*")
    add_git_tag(tag: "v#{version_number}-#{build_number}")
    push_to_git_remote
    sentry_upload_dif(
      org_slug: 'verse',
      project_slug: 'nos-ios',
      include_sources: true, 
      url: 'https://sentry.nos.social'
    )
    notification(
      subtitle: "Build uploaded", 
      message: "tap to open App Store Connect", 
      sound: "Pebble", 
      open: "https://appstoreconnect.apple.com/apps/1670125746/testflight/ios"
    )
  end

  desc "Refresh certificates in the match repo"
  lane :certs do
    app_store_connect_api_key(
      key_id: asc_key_id,
      issuer_id: asc_issuer_id,
      key_content: asc_key_content
    )
    match(type: "appstore")
    match(type: "development")
  end

  desc "Clean App Store Connect of certificates"
  lane :nuke_certs do
    app_store_connect_api_key(
      key_id: asc_key_id,
      issuer_id: asc_issuer_id,
      #key_filepath: "~/.fastlane/AuthKey_4L8Z9W89TJ.p8"
      key_content: asc_key_content
    )
    match_nuke(type: "appstore")
  end
end

# Dynamically define 3 lanes:
# bump_major
# bump_minor
# bump_patch
# from: https://benscheirman.com/2020/10/managing-version-numbers-with-fastlane/
%w{major minor patch}.each do |part|
  lane "bump_#{part}".to_sym do
    increment_version_number_in_xcodeproj(bump_type: part, target: "Nos")
  end
end

