# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "XV586PG63R",
      issuer_id: "8985ca52-aba6-4f7a-91bb-d052a5b030fa",
      key_filepath: "~/.fastlane/AuthKey_XV586PG63R.p8"
    )
    increment_build_number(xcodeproj: "Nos.xcodeproj")
    version_number = get_version_number
    build_number = get_build_number
    gym(scheme: "Nos", clean: true)
    changelog = read_changelog
    upload_to_testflight(changelog: changelog)
    stamp_changelog(section_identifier: "#{version_number} (#{build_number})")
  end
end

# Dynamically define 3 lanes:
# bump_major
# bump_minor
# bump_patch
# from: https://benscheirman.com/2020/10/managing-version-numbers-with-fastlane/
%w{major minor patch}.each do |part|
  lane "bump_#{part}".to_sym do
    increment_version_number_in_xcodeproj(bump_type: part, target: "Nos")
  end
end

